name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Notify Slack - CI Started
      run: |
        $payload = @{
          text = "🚀 CI started for *${{ github.repository }}* on *${{ github.ref_name }}* by *${{ github.actor }}*."
        } | ConvertTo-Json -Compress
        Invoke-RestMethod -Uri "${{ secrets.SLACK_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $payload
      shell: pwsh

    - name: Checkout
      uses: actions/checkout@v4

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
        version: '9.6.0'
        projectPath: '${{ github.workspace }}'
        args: >
          -noSplash 
          -retry=0 
          -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" 
          -apiKey=${{ secrets.API_KEY }} 
          --config -webui.autoUpdateDrivers=true

    - name: Notify Slack - Success
      if: success()
      run: |
        $payload = @{
          text = "✅ CI passed for *${{ github.repository }}* on *${{ github.ref_name }}*."
        } | ConvertTo-Json -Compress
        Invoke-RestMethod -Uri "${{ secrets.SLACK_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $payload
      shell: pwsh

    - name: Notify Slack - Failure
      if: failure()
      run: |
        $payload = @{
          text = "❌ CI failed for *${{ github.repository }}* on *${{ github.ref_name }}*. Check the logs."
        } | ConvertTo-Json -Compress
        Invoke-RestMethod -Uri "${{ secrets.SLACK_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $payload
      shell: pwsh
