# .github/workflows/trigger-repo2.yml
name: Trigger Repo2 Workflow on Push

on:
  push:  # Trigger when code is pushed to any branch
    branches:
      - master

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo2 workflow via GitHub API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.KATALON_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/abhiramdas99/skillbuilder-qa-automation/actions/workflows/katalon.yml/dispatches \
            -d '{"ref":"master"}'
